language: csharp
solution: Orion.sln
sudo: required
install:
  - chmod a+x ./tools/ContinuousIntegration/Build/generateCoverageConfig.sh
script:
  - make compile
after_script:
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory tools
  - mono ./tools/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./Orion.Tests/bin/Release/Orion.Tests.dll
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -f ./coverageResults.txt
